#!/bin/bash
# Atom: Common ignore file patterns for AI coding tools
# Provides standardized ignore patterns used across different AI assistants

# Common ignore patterns based on research from:
# - Cursor (.cursorignore)
# - Cline (.clineignore)
# - Continue.dev (.continueignore)
# - GitHub Copilot (.copilotignore)
# - Roo Code (.rooignore)

# Get common ignore patterns that apply to all tools
get_common_ignore_patterns() {
    cat << 'EOF'
# Dependencies
node_modules/
**/node_modules/
.pnp
.pnp.js
vendor/
gems/

# Build outputs
/build/
/dist/
/.next/
/out/
/target/
bin/
Build/
*.o
*.obj
*.exe
*.dll
*.so
*.dylib

# Testing
/coverage/
.pytest_cache/
.vscode-test/
__pycache__/

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
.env.*

# Security-sensitive files
*.key
*.pem
*.p12
*.pfx
*.crt
*.cer
*.jks
*.keystore
*.truststore
*.secret
*.secrets
credentials
credentials.*
auth.json
token
token.*
*.token

# IDE and editor directories
.vscode/
.idea/
.vs/
.eclipse/
.settings/

# Version control
.git/
.svn/
.hg/

# Package manager files
package-lock.json
yarn.lock
pnpm-lock.yaml
composer.lock
Gemfile.lock
poetry.lock
Pipfile.lock
go.sum
*.lock

# Logs
*.log
logs/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Temporary files
*.tmp
*.temp
*.swp
*.swo
*.bak
*.backup
*.old
*.orig

# Media and binary files
*.png
*.jpg
*.jpeg
*.gif
*.ico
*.svg
*.mp4
*.mp3
*.avi
*.mov
*.mkv
*.webm
*.pdf
*.zip
*.tar
*.gz
*.tgz
*.rar
*.7z

# Font files
*.ttf
*.woff
*.woff2
*.eot

# Database files
*.db
*.sqlite
*.sqlite3
*.mdb
*.accdb

# Data files
*.csv
*.xlsx
*.xls
*.parquet
*.jsonl

# Compiled and minified files
*.min.js
*.min.css
*.bundle.js
*.bundle.css
*.map

# OS-specific files
.DS_Store
Thumbs.db

# Cache directories
.cache/
.gradle/
.mvn/
.npm/

# Python-specific
*.pyc
*.pyo
*.pyd
__pycache__/
site-packages/
.venv/
venv/
env/

# Java-specific
*.class
*.jar
*.war
*.ear

# Rust-specific
Cargo.lock

# Go-specific
go.sum

# Other
*.gcda
*.gcno
*.profraw
*.wasm
*.uasset
*.pdb
*.bin
*.pag
EOF
}

# Get security-focused patterns (more restrictive)
get_security_ignore_patterns() {
    cat << 'EOF'
# SSH and GPG
id_rsa
id_dsa
id_ecdsa
id_ed25519
*.ppk
*.gpg
.ssh/
.gnupg/
.gpg/

# Cloud provider credentials
.aws/
.gcp/
.azure/
.kube/
.docker/

# Secret directories
secrets/
.secrets/
private/
.private/
certs/
certificates/
keys/

# Backup files that might contain sensitive data
*.bak
*.backup
*.old
*.orig

# Docker secrets
docker-compose.override.yml
docker-compose.override.yaml

# Temporary directories with potential sensitive data
tmp/secrets/
temp/secrets/
.tmp/
EOF
}

# Get tool-specific additions for Cursor
get_cursor_specific_patterns() {
    cat << 'EOF'
# Cursor-specific ignores
.cursor/
EOF
}

# Get tool-specific additions for Cline
get_cline_specific_patterns() {
    cat << 'EOF'
# Cline-specific ignores
# Use !include directive to reference other ignore files
# Example: !include .gitignore
EOF
}

# Get tool-specific additions for Continue
get_continue_specific_patterns() {
    cat << 'EOF'
# Continue.dev-specific ignores
.continue/
EOF
}

# Get tool-specific additions for Copilot
get_copilot_specific_patterns() {
    cat << 'EOF'
# GitHub Copilot-specific ignores
# Note: Copilot also respects .gitignore
EOF
}

# Get tool-specific additions for Roo Code
get_roocode_specific_patterns() {
    cat << 'EOF'
# Roo Code-specific ignores
# Files excluded by .rooignore but not by .gitignore will still be checkpointed
EOF
}

# Generate complete ignore file for a specific tool
# Args: $1 = tool name (cursor, cline, continue, copilot, roocode)
generate_ignore_file() {
    local tool="$1"
    
    # Common header
    echo "# Auto-generated ignore file for $tool"
    echo "# Generated by ainish-coder"
    echo "# Edit this file to customize what $tool ignores"
    echo ""
    
    # Common patterns
    get_common_ignore_patterns
    echo ""
    
    # Security patterns
    echo "# Security-sensitive patterns"
    get_security_ignore_patterns
    echo ""
    
    # Tool-specific patterns
    case "$tool" in
        cursor)
            get_cursor_specific_patterns
            ;;
        cline)
            get_cline_specific_patterns
            ;;
        continue)
            get_continue_specific_patterns
            ;;
        copilot)
            get_copilot_specific_patterns
            ;;
        roocode|roo)
            get_roocode_specific_patterns
            ;;
    esac
}
