#!/bin/bash
# MOLECULE: Cline deployment
# Comprehensive Cline configuration deployment:
# - Creates single .clinerules file (merged AGENTS.md + MAIRULES.md)
# - Ignore files
# Note: Cline uses .clinerules as a SINGLE FILE, not a directory
# Requires AGENTS.md and MAIRULES.md to exist first

deploy_cline() {
    local target_dir="${1:-.}"  # Default to current directory if not provided
    local source_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
    
    validate_target_dir "$target_dir" || return 1
    require_agents_md "$target_dir" || return 1
    require_mairules_md "$target_dir" || return 1
    
    echo -e "${BRIGHT_BLUE}Deploying Full Cline Configuration${RESET}"
    
    local clinerules_file="$target_dir/.clinerules"
    
    # Create .clinerules as single merged file
    # Backup existing file if present
    if [[ -f "$clinerules_file" ]]; then
        mv "$clinerules_file" "$clinerules_file.backup"
        echo -e "${YELLOW}Backed up existing .clinerules${RESET}"
    fi
    
    # Create merged .clinerules file
    {
        echo "# Cline Rules"
        echo ""
        echo "<!-- This file is auto-generated by ainish-coder -->"
        echo "<!-- Source: AGENTS.md + MAIRULES.md -->"
        echo ""
        echo "---"
        echo ""
        cat "$target_dir/AGENTS.md"
        echo ""
        echo "---"
        echo ""
        cat "$target_dir/MAIRULES.md"
    } > "$clinerules_file"
    
    if [[ -f "$clinerules_file" ]]; then
        echo -e "${GREEN}✓ Created: .clinerules (merged AGENTS.md + MAIRULES.md)${RESET}"
    else
        echo -e "${BRIGHT_RED}Error: Failed to create .clinerules${RESET}"
        return 1
    fi
    
    echo -e "${BRIGHT_GREEN}✅ Cline fully configured${RESET}"
    echo -e "${BLUE}💡 .clinerules file contains all project rules${RESET}"
    echo -e "${BLUE}💡 Use Cline's built-in /newtask and /newrule commands for workflows${RESET}"
    return 0
}
