#!/bin/bash
# MOLECULE: Gitignore deployment
# Creates a comprehensive .gitignore file for AI-assisted development projects
# Includes patterns for AI tools, environments, and common development artifacts

deploy_gitignore() {
    local target_dir="${1:-.}"  # Default to current directory if not provided
    
    validate_target_dir "$target_dir" || return 1
    
    echo -e "${BRIGHT_BLUE}Deploying .gitignore configuration${RESET}"
    
    local gitignore_file="$target_dir/.gitignore"
    
    # Backup existing .gitignore if it exists
    if [[ -f "$gitignore_file" ]]; then
        local backup_file=$(create_backup "$gitignore_file")
        if [[ $? -eq 0 ]]; then
            echo -e "${YELLOW}⚠️  Backed up existing .gitignore to: $backup_file${RESET}"
        else
            echo -e "${BRIGHT_RED}Error: Failed to backup existing .gitignore${RESET}"
            return 1
        fi
    fi
    
    # Create comprehensive .gitignore
    cat > "$gitignore_file" << 'EOF'
# AINISH Coder - Comprehensive Git Ignore Patterns
# Generated by ainish-coder --gitignore

# ═══════════════════════════════════════════════════════════
# AI PAIR PROGRAMMER FILES
# ═══════════════════════════════════════════════════════════
.cursor/
.cursorrules
.github/copilot-instructions.md
.github/instructions/
.gemini/
.qwen/
.claude/
.continue/
.clinerules/
.windsurf/
.roo/
.aider*
.aide/

# ═══════════════════════════════════════════════════════════
# ENVIRONMENT AND SECRETS
# ═══════════════════════════════════════════════════════════
.env
.env.*
!.env.example
*.env.local
*.env.development
*.env.test
*.env.production
*.key
*.pem
*.p12
*.pfx
*.crt
*.csr
*.jks
*.keystore
secrets/
.secrets/

# ═══════════════════════════════════════════════════════════
# PYTHON
# ═══════════════════════════════════════════════════════════
# Virtual environments
venv/
venv.bak/
venv.*
.venv/
ENV/
env/
.conda/
.python-version
*/.env
*/*env.*
!*env.example

# Cache and build artifacts
__pycache__/
*.pyc
*.pyo
*.pyd
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Testing and coverage
.coverage
htmlcov/
.pytest_cache/
.tox/
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/
.mypy_cache/
.dmypy.json
dmypy.json

# ═══════════════════════════════════════════════════════════
# NODE.JS / JAVASCRIPT
# ═══════════════════════════════════════════════════════════
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.npm
.eslintcache
.node_repl_history
*.tgz
.yarn-integrity
.pnp.*
.yarn/
.next/
out/
.nuxt/
.cache/

# ═══════════════════════════════════════════════════════════
# IDE AND EDITOR FILES
# ═══════════════════════════════════════════════════════════
.vscode/
.idea/
*.swp
*.swo
*~
.project
.classpath
.settings/
*.sublime-project
*.sublime-workspace

# ═══════════════════════════════════════════════════════════
# OS GENERATED FILES
# ═══════════════════════════════════════════════════════════
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
desktop.ini

# ═══════════════════════════════════════════════════════════
# LOGS AND TEMPORARY FILES
# ═══════════════════════════════════════════════════════════
*.log
*.tmp
*.temp
logs/
temp/
tmp/
*.pid
*.seed
*.pid.lock

# ═══════════════════════════════════════════════════════════
# DOCUMENTATION BUILD ARTIFACTS
# ═══════════════════════════════════════════════════════════
docs/_build/
docs/build/
site/
_build/
build/
public/
dist/

# ═══════════════════════════════════════════════════════════
# DATABASE FILES
# ═══════════════════════════════════════════════════════════
*.db
*.sqlite
*.sqlite3
*.db-journal

# ═══════════════════════════════════════════════════════════
# BACKUP FILES
# ═══════════════════════════════════════════════════════════
*.bak
*.backup
*.old
*.orig
*.rej
*.swp
*.swo

# ═══════════════════════════════════════════════════════════
# COMPILED FILES
# ═══════════════════════════════════════════════════════════
*.com
*.class
*.dll
*.exe
*.o
*.so
*.dylib

# ═══════════════════════════════════════════════════════════
# PACKAGE AND ARCHIVE FILES
# ═══════════════════════════════════════════════════════════
*.tar
*.gz
*.bz2
*.xz
*.zip
*.rar
*.7z
*.deb
*.rpm
*.msi
*.dmg
*.pkg

# ═══════════════════════════════════════════════════════════
# MEDIA FILES (uncomment if needed)
# ═══════════════════════════════════════════════════════════
# *.png
# *.jpg
# *.jpeg
# *.gif
# *.svg
# *.ico
# *.pdf
# *.mp4
# *.mp3
# *.wav
# *.avi
# *.mov

EOF
    
    if [[ -f "$gitignore_file" ]]; then
        echo -e "${GREEN}✓ Created: .gitignore${RESET}"
        echo -e "${BRIGHT_GREEN}✅ Gitignore configured${RESET}"
        return 0
    else
        echo -e "${BRIGHT_RED}Error: Failed to create .gitignore${RESET}"
        return 1
    fi
}
